name: build-c
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
      - 2-cc-cache-images
    paths:
      - '.github/workflows/build-c.yml'
      - 'build/c/Dockerfile'
  pull_request:
    branches:
      - main
      - 2-cc-cache-images
    paths:
      - '.github/workflows/build-c.yml'
      - 'build/c/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 18.04, 20.04, 22.04 ]
        build: [ x86_64-w64-mingw32, i686-w64-mingw32, x86_64-unknown-linux-gnu, i686-pc-linux-gnu, arm-linux-gnueabihf, aarch64-linux-gnu, riscv64-linux-gnu, x86_64-unknown-freebsd]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/c/Dockerfile
          build-args: |
            VERSION=ubuntu:${{ matrix.version }}
            BUILD=${{ matrix.build }}
            THREADS=2
          cache-to: ghcr.io/dappserver/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }}
          cache-from: ghcr.io/dappserver/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }}
          push: true
          tags: lthn/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }},ghcr.io/dappserver/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }}
      - name: Docker Build
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/c/Dockerfile
          build-args: |
            VERSION=ubuntu:${{ matrix.version }}
            BUILD=${{ matrix.build }}
            THREADS=2
          cache-to: ghcr.io/dappserver/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }}
          cache-from: ghcr.io/dappserver/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }}
          push: false
          tags: lthn/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }},ghcr.io/dappserver/build-c:ubuntu-${{ matrix.version }}-depends-${{ matrix.build }}

